spring.application.name=InovaTech
spring.docker.compose.enabled=false

# Server Configuration
server.port=5000

# Configurações do banco H2 (em memória)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

# Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# SpringDoc OpenAPI 3 (Swagger)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

# Propriedades customizadas da aplicação
printgoldenticket=false
UrlSts=http://localhost:8080/mock/sts
x-getnet-flowID=mock-flow-id
x-getnet-correlationID=mock-correlation-id
client_id=mock-client-id
client_secret=mock-client-secret
useProxy=false
UrlMailing=http://localhost:8080/mock/mailing
